Update udemy-cka-v222.yml

diff --git a/udemy-cka-v222.yml b/udemy-cka-v222.yml
--- a/udemy-cka-v222.yml
+++ b/udemy-cka-v222.yml
@@ -171,3 +171,43 @@ status:
     name: http
 
 
+
+cat curl-test.sh 
+for i in {1..35}; do
+   kubectl exec --namespace=kube-public curl -- sh -c 'test=`wget -qO- -T 2  http://webapp-service.default.svc.cluster.local:8080/info 2>&1` && echo "$test OK" || echo "Failed"';
+   echo ""
+done
+
+kubectl set image deployment/frontend  simple-webapp=kodekloud/webapp-color:v2
+
+
+kubectl run static-busybox --image=busybox --restart=Never --command sleep 300
+
+
+
+ROM python:3.6-alpine
+
+RUN pip install flask
+
+COPY . /opt/
+
+EXPOSE 8080
+
+WORKDIR /opt
+
+ENTRYPOINT ["python", "app.py"]
+
+
+FROM python:3.6-alpine
+
+RUN pip install flask
+
+COPY . /opt/
+
+EXPOSE 8080
+
+WORKDIR /opt
+
+ENTRYPOINT ["python", "app.py"]
+
+CMD ["--color", "red"]
